### ISSUE TITLE
Sample crashes at startup

### ISSUE THREAD

**Issue by e1itconsult** [maciej-czekala/corona_business_app_base_template#1]
Hi,
tried your sample app on windows with corona sdk Build: 2017.3135
App crashes on simulator at startup:

06:12:21.119  splash created
06:12:21.119  splash show
06:12:22.117  splash created
06:12:22.117  ERROR: Runtime error
06:12:22.117  ?:0: attempt to index field '?' (a nil value)
06:12:22.117  stack traceback:
06:12:22.117  	?: in function 'get'
06:12:22.117  	C:\Users\atisfrit\OneDrive\_Development\_Corona\02_Samples\corona_business_app_base_template-master\app\scenes\home\home_view.lua:10: in function 'View'
06:12:22.117  	C:\Users\atisfrit\OneDrive\_Development\_Corona\02_Samples\corona_business_app_base_template-master\app\scenes\home\home.lua:65: in function 'onCreate'
06:12:22.117  	?: in function 'goTo'
06:12:22.117  	C:\Users\atisfrit\OneDrive\_Development\_Corona\02_Samples\corona_business_app_base_template-master\app\scenes\splash\splash.lua:45: in function '_listener'
06:12:22.117  	?: in function '?'
06:12:22.117  	?: in function <?:190>

**Comment by maciej-czekala** [comment]
Hi,

Thanks for testing. I just fixed the problem. Please download updated version and try again.

Regards

**Comment by e1itconsult** [comment]
Hi,

 

tried it and works fine now, thx!

 

Also tried your ui framework, but havinng also some issues:

 

https://github.com/maciej-czekala/corona_ui_framework/issues/3

 

seems to be a probelm with your function  ui.screen.toPx

 

Regards

Andreas

 

 

 


Gesendet: Mittwoch, 17. Januar 2018 um 09:03 Uhr
Von: "Maciej Czekala" <notifications@github.com>
An: maciej-czekala/corona_business_app_base_template <corona_business_app_base_template@noreply.github.com>
Cc: pucman68 <andreas.fritzenwallner@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [maciej-czekala/corona_business_app_base_template] Sample crashes at startup (#1)


Hi,

Thanks for testing. I just fixed the problem. Please download updated version and try again.

Regards
